name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore MTOGO.Tests/MTOGO.Tests.csproj  # Restore dependencies for the test project
    - name: Build
      run: dotnet build MTOGO.Tests/MTOGO.Tests.csproj --no-restore  # Build the test project
    - name: Test
      run: dotnet test MTOGO.Tests/MTOGO.Tests.csproj --no-build --verbosity normal  # Run the tests in the test project
